### PR TITLE
Native Drag API

### PR DESCRIPTION
**Pull request by joyblanks**
**Changes:**
- Added code for HTML native drag API.
  `settings.nativeDrag = true` should drag the popup window with HTML native drag/drop API
  `settings.nativeDrag = false` should drag the popup window with mouse (up/down/move) existing API

- Updated min.js with latest code
- Added a min.css

### CODE REVIEW

**Comment by joyblanks** [comment]
@gasparesganga Ok I completely missed the formatting my editor was on auto format.

New Pull Request, I have not changed any structure. Since you already have a plan ahead.

**Comment by gasparesganga** [comment]
Great, thank you!

**Comment by joyblanks** [comment]
@gasparesganga Can you please update the CDN. I wish to use it


Thanks.
Joy

**Comment by gasparesganga** [comment]
Sure! A CDN update will happen automatically with a new release, I'm doing it right now.

**Comment by totpero** [comment]
this is not completed, see  #9

**Pull request merged**
